# Generated by Django 5.1.4 on 2025-01-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('name_accounts', models.CharField(max_length=200)),
                ('matury', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('annotation', models.CharField(max_length=200)),
            ],
        ),
    ]
