# Generated by Django 5.1.4 on 2025-01-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_contas_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='opcao',
            field=models.BooleanField(default=False, verbose_name='Sim ou Não'),
        ),
    ]
