# Generated by Django 5.1.4 on 2025-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_contas_opcao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='opcao',
            new_name='pay',
        ),
    ]
