# Generated by Django 5.1.4 on 2025-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('type_card', models.CharField(max_length=100)),
                ('closing', models.IntegerField(blank=True, null=True)),
                ('matury', models.DateField(blank=True, null=True)),
                ('limit_card', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
