# Generated by Django 5.1.4 on 2025-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='matury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='owner',
        ),
        migrations.AddField(
            model_name='cartao',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to='owner.dono'),
        ),
    ]
