# Generated by Django 5.1.4 on 2025-01-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recebiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('Depositor', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTÂO', 'Cartão'), ('CHEQUE', 'Cheque')], max_length=100, null=True)),
                ('resume', models.TextField(blank=True, max_length=500, null=True)),
                ('entries_of', models.ManyToManyField(related_name='entries_of', to='owner.dono')),
            ],
        ),
    ]
