# Generated by Django 5.1.4 on 2025-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receivables', '0002_rename_depositor_recebiveis_depositor'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebiveis',
            name='entries_of',
        ),
        migrations.AddField(
            model_name='recebiveis',
            name='name',
            field=models.ManyToManyField(related_name='recebiveis', to='owner.dono'),
        ),
    ]
